Lection 1
OlyaChistikova/SimbirSoft pull request #3
Opened 2024-10-20 13:34 UTC by OlyaChistikova

2024-11-01 08:10 UTC, DS-170 requested changes
Оставил несколько комментариев, которые нужно поправить, в остальном все соответствует заданию

2024-11-01 08:10 UTC, DS-170 commented on src/SimbirSoft/ModelCar/Car.java
>  interface Drivable{
Нарушение ООП, интерфейсы должны лежать отдельно

2024-11-01 08:10 UTC, DS-170 commented on src/SimbirSoft/ModelCar/Car.java
>  import java.util.Objects;
Неиспользуемые импорты лучше удалять. Для автоматизации этого есть мастхэвные хоткеи в IntelIJ IDEA 1. ctrl+alt+O = удаление всех неиспользуемых импортов в классе, 2. ctrl+alt+L = форматирование текста под заданный формат в настройках (лучше сразу настроить [Google code style](https://javarush.com/groups/posts/2009-intellij-idea-stiljh-i-formatirovanie-koda))

2024-11-03 15:17 UTC, merged

2024-11-03 15:48 UTC, OlyaChistikova commented
Удалила случайно пул